version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: lifo_db
    ports:
      - "5432:5432"
  app:
    container_name: app
    build:
      context: .
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
